/**
 * Verified ERC20 token presets for Starknet sepolia.
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: npx tsx scripts/generate-presets.ts --network sepolia
 * Source: AVNU API (https://sepolia.api.avnu.fi)
 */

import type { Token, Address } from "@/types";

export const sepoliaTokens: Record<string, Token> = {
  /** Ether */
  ETH: {
    name: "Ether",
    address:
      "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7" as Address,
    decimals: 18,
    symbol: "ETH",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png"
      ),
    },
  },
  /** Starknet Token */
  STRK: {
    name: "Starknet Token",
    address:
      "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d" as Address,
    decimals: 18,
    symbol: "STRK",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/26433/small/starknet.png"
      ),
    },
  },
  /** USDC */
  USDC: {
    name: "USDC",
    address:
      "0x0512feac6339ff7889822cb5aa2a86c848e9d392bb0e3e237c008674feed8343" as Address,
    decimals: 6,
    symbol: "USDC",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png"
      ),
    },
  },
  /** USDC.e */
  USDC_E: {
    name: "USDC.e",
    address:
      "0x053b40a647cedfca6ca84f542a0fe36736031905a9639a7f19a3c1e66bfd5080" as Address,
    decimals: 6,
    symbol: "USDC.e",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png"
      ),
    },
  },
  /** Wrapped liquid staked Ether 2.0 */
  WSTETH: {
    name: "Wrapped liquid staked Ether 2.0",
    address:
      "0x030de54c07e57818ae4a1210f2a3018a0b9521b8f8ae5206605684741650ac25" as Address,
    decimals: 18,
    symbol: "wstETH",
    metadata: {
      logoUrl: new URL(
        "https://static.starkscan.co/tokens/0x042b8f0484674ca266ac5d08e4ac6a3fe65bd3129795def2dca5c34ecc5f96d2/icons/QmaxTVxd6ZWrotuG64LiuL8PCEgwjiHiQF9isCu8QKgneP"
      ),
    },
  },
  /** PastaSwap */
  PASTA: {
    name: "PastaSwap",
    address:
      "0x052f3eaa6c94a8abab8b277ac8405f97ff73c07c0b8ac937bb3e93dd934e6787" as Address,
    decimals: 18,
    symbol: "PASTA",
    metadata: {
      logoUrl: new URL("https://i.postimg.cc/sgpzCv0Z/logo.png"),
    },
  },
} as const;
