import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollView: { flex: 1 },
  content: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 120,
    gap: 14,
  },
  header: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 12 },
  networkPill: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  networkPillText: { fontSize: 11, fontWeight: "600" },
  card: {
    width: "100%",
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    gap: 12,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardTitle: { fontSize: 16, fontWeight: "700" },
  label: {
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  smallText: { fontSize: 12 },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  addressRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  addressButton: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  tokenRow: { flexDirection: "row", alignItems: "center", gap: 12, flex: 1 },
  poolRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  collateralRow: { flexDirection: "row", alignItems: "center", minHeight: 26 },
  sponsoredRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sponsoredSwitch: {
    flexDirection: "row",
    backgroundColor: "#e5e5e5",
    borderRadius: 999,
    padding: 2,
    gap: 2,
  },
  sponsoredSegment: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  sponsoredSegmentSelected: { backgroundColor: "#000" },
  sponsoredText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#111",
    textTransform: "uppercase",
  },
  refreshButton: {
    width: 28,
    height: 28,
    borderRadius: 999,
    justifyContent: "center",
    alignItems: "center",
  },
  metricsRowPair: { flexDirection: "row", gap: 10 },
  metricCard: { flex: 1, gap: 4 },
  metricLabel: { fontSize: 11, textTransform: "uppercase", letterSpacing: 0.4 },
  metricValueBold: { fontSize: 16, fontWeight: "700" },
  amountLabelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  amountRow: {
    borderWidth: 1,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
  },
  amountInput: {
    flex: 1,
    fontSize: 18,
    paddingVertical: 10,
    fontWeight: "600",
  },
  percentSuffix: {
    fontSize: 16,
    fontWeight: "700",
    paddingLeft: 8,
  },
  maxButton: { borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6 },
  maxButtonText: {
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  submitButton: {
    width: "100%",
    marginTop: 4,
    borderRadius: 12,
    minHeight: 48,
    justifyContent: "center",
    alignItems: "center",
  },
  submitButtonText: { fontSize: 15, fontWeight: "700" },
  secondaryButton: {
    width: "100%",
    borderRadius: 12,
    borderWidth: 1,
    minHeight: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  secondaryButtonText: { fontSize: 14, fontWeight: "700" },
  errorText: { color: "#e53935", fontSize: 12, fontWeight: "600" },
  footerHint: { width: "100%", textAlign: "center", fontSize: 12 },
  modalContainer: { flex: 1 },
  modalHeader: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  closeButton: { borderRadius: 8, paddingHorizontal: 12, paddingVertical: 6 },
  closeButtonText: { fontSize: 12, fontWeight: "600" },
  marketCardGrid: { flexDirection: "row", flexWrap: "wrap", gap: 14 },
  marketCard: { borderWidth: 1, borderRadius: 18, padding: 16, gap: 16 },
  marketCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  marketCardSymbol: { fontSize: 18, fontWeight: "800" },
  selectedPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  selectedPillText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    rowGap: 14,
    columnGap: 10,
  },
  metricCell: { width: "48%", gap: 4 },
  metricValue: { fontSize: 16, fontWeight: "700" },
  marketCardButton: {
    backgroundColor: "#dbe1ff",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  marketCardButtonText: { color: "#2c42c9", fontSize: 15, fontWeight: "700" },
  tabRow: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 4,
    flexDirection: "row",
    gap: 6,
  },
  tabButton: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  tabButtonActive: { backgroundColor: "#000" },
  tabText: { fontSize: 14, fontWeight: "700" },
  noticeCard: { borderWidth: 1, borderRadius: 14, padding: 14, gap: 6 },
  positionRow: { borderRadius: 10, padding: 10, gap: 2 },
  positionLabel: { fontSize: 11, fontWeight: "600", opacity: 0.6 },
  positionValue: { fontSize: 14, fontWeight: "700" },
  positionBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#dcfce7",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  positionBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#15803d",
  },
  positionDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  positionDetailLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#166534",
  },
  positionDetailValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#15803d",
  },
  toggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: 12,
    padding: 12,
  },
  toggleLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  toggleLabelText: {
    fontSize: 13,
    fontWeight: "700",
  },
  toggleButtons: {
    flexDirection: "row",
    gap: 4,
  },
  toggleButton: {
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
});
